#!/usr/bin/env python3
# -*- coding: UTF=8 -*-

"""
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


def even_fib():
    sub1 = 0
    sub2 = 1
    cur = 0
    sum = 0
    while cur < 4*(10**6):
        cur = sub1 + sub2
        if cur % 2 == 0:
            sum += cur
        sub1 = sub2
        sub2 = cur
    return sum


if __name__ == "__main__":
    print(even_fib())
